CREATE TABLE TB_SFPY_USER(
	USER_ID INTEGER NOT NULL PRIMARY KEY,
	USER_NAME VARCHAR2(64),
	USER_PWD   VARCHAR2(64),
	USER_REALLY_NAME VARCHAR2(64),
	USER_STATUS INTEGER,
	USER_SEX INTEGER,
	USER_AGE INTEGER,
	USER_ADDRESS VARCHAR2(512),
	USER_EMAIL VARCHAR2(128),
	USER_REMAKER VARCHAR2(5 12)
);
CREATE SEQUENCE GEN_SFPY_USER INCREMENT BY 1 START WITH 1
    NOMAXVALUE NOCYCLE CACHE 10;

CREATE OR REPLACE TRIGGER TR_SFPY_USER
    BEFORE INSERT ON TB_SFPY_USER FOR EACH ROW
BEGIN
    SELECT GEN_SFPY_USER.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
END;
