--管理员表--
CREATE TABLE TB_SFPY_ADMIN(
	OBMS_ID INTEGER NOT NULL PRIMARY KEY,
	OBMS_PSWD VARCHAR2(20),
	OBMS_STATUS INTEGER,
	OBMS_TIME TIMESTAMP
);
CREATE SEQUENCE GEN_SFPY_ADMIN INCREMENT BY 1 START WITH 1
    NOMAXVALUE NOCYCLE CACHE 10;

CREATE OR REPLACE TRIGGER TR_SFPY_ADMIN
    BEFORE INSERT ON TB_SFPY_USER FOR EACH ROW
BEGIN
    SELECT GEN_SFPY_ADMIN.NEXTVAL INTO :NEW.OBMS_ID FROM DUAL;
END;

--客户基本信息表--
CREATE TABLE TB_SFPY_CLIENT(
	CLIENT_ID INTEGER NOT NULL PRIMARY KEY,
	CLIENT_NAME VARCHAR2(30),
	CLIENT_PSWD VARCHAR2(30),
	CLIENT_REALLY_NAME VARCHAR2(30),
	CLIENT_IDENTITY VARCHAR2(18),
	CLIENT_BALANCE NUMBER(15,4),
	CLIENT_STATUS INTEGER,
	CLIENT_ADDRESS VARCHAR(256),
	CLIENT_ACCOUNT_CODE VARCHAR(11),
	CLIENT_BANK_ID INTEGER,
	CLIENT_TIME TIMESTAMP
);

CREATE SEQUENCE GEN_SFPY_CLIENT INCREMENT BY 1 START WITH 1
    NOMAXVALUE NOCYCLE CACHE 10;

CREATE OR REPLACE TRIGGER TR_SFPY_CLIENT
    BEFORE INSERT ON TB_SFPY_CLIENT FOR EACH ROW
BEGIN
    SELECT GEN_SFPY_CLIENT.NEXTVAL INTO :NEW.CLIENT_ID FROM DUAL;
END;

--银行存款信息表--
CREATE TABLE TB_SFPY_BANKIN(
	BANKIN_ID INTEGER NOT NULL PRIMARY KEY,
	CLIENT_ID INTEGER,
	BANKIN_TIME TIMESTAMP,
	BANKIN_MONEY NUMBER(15,4),
	CLIENT_BALANCE NUMBER(15,4)
);
CREATE SEQUENCE GEN_SFPY_BANKIN INCREMENT BY 1 START WITH 1
    NOMAXVALUE NOCYCLE CACHE 10;

CREATE OR REPLACE TRIGGER TR_SFPY_BANKIN
    BEFORE INSERT ON TB_SFPY_BANKIN FOR EACH ROW
BEGIN
    SELECT GEN_SFPY_BANKIN.NEXTVAL INTO :NEW.BANKIN_ID FROM DUAL;
END;

--银行取款信息表--
CREATE TABLE TB_SFPY_BANKOUT(
	BANKOUT_ID INTEGER NOT NULL PRIMARY KEY,
	CLIENT_ID INTEGER,
	BANKOUT_TIME TIMESTAMP,
	BANKOUT_MONEY NUMBER(15,4),
	CLIENT_BALANCE NUMBER(15,4)
);
CREATE SEQUENCE GEN_SFPY_BANKOUT INCREMENT BY 1 START WITH 1
    NOMAXVALUE NOCYCLE CACHE 10;

CREATE OR REPLACE TRIGGER TR_SFPY_BANKOUT
    BEFORE INSERT ON TB_SFPY_BANKOUT FOR EACH ROW
BEGIN
    SELECT GEN_SFPY_BANKOUT.NEXTVAL INTO :NEW.BANKOUT_ID FROM DUAL;
END;

--银行客户转账信息表--
CREATE TABLE TB_SFPY_TRANSFER(
	OBMS_ID INTEGER NOT NULL PRIMARY KEY,
	CLIENT_ID INTEGER,
	TRANSFER_ID INTEGER,
	TRANSFER_TIME TIMESTAMP,
	TRANSFER_MONEY TIMESTAMP,
	CLIENT_BALANCE NUMBER(15,4)
);
CREATE SEQUENCE GEN_SFPY_TRANSFER INCREMENT BY 1 START WITH 1
    NOMAXVALUE NOCYCLE CACHE 10;

CREATE OR REPLACE TRIGGER TR_SFPY_TRANSFER
    BEFORE INSERT ON TB_SFPY_TRANSFER FOR EACH ROW
BEGIN
    SELECT GEN_SFPY_TRANSFER.NEXTVAL INTO :NEW.OBMS_ID FROM DUAL;
END;

--测试帐号--
insert into tb_sfpy_client t (t.client_name, t.client_pswd, t.CLIENT_REALLY_NAME, client_identity, t.client_balance, t.client_status, t.client_address, t.client_account_code, t.client_bank_id)
values('admin', 'admin','管理员', 320322199212176213, 9999.99, 10, '中国南京', '12345678903', 30);
























